### ISSUE TITLE
배포 대응 - 스팩 아웃 계정 삭제, 정보초기화 | 노션 링크 연결 

### ISSUE THREAD

**Issue by SenseCodeValue** [depromeet/11th_7team_web#295]
## 할 일

- [ ]

**Comment by hyesungoh** [comment]
서비스 이용약관
https://www.notion.so/e75b7f51da7944508f37071f5345cc46

개인정보정책
https://www.notion.so/94ac34de4c97467fb1f21a8bbed26eab

👍 👍 👍 👍
