### ISSUE TITLE
텍스트 필드에 그림자 생기는 현상

### ISSUE THREAD

**Issue by ddarkr** [depromeet/11th_7team_web#314]
## 설명

<img width="791" alt="image" src="https://user-images.githubusercontent.com/6638675/170962943-afe3ad02-f3ce-4ea8-9a45-e6ce25ca1ae0.png">

iOS 버전이 낮아서 생기는 이슈인듯

## 할 일

- [ ]

**Comment by SenseCodeValue** [comment]
악...이거 ios 종특

**Comment by ddarkr** [comment]
@SenseCodeValue 웹 개발자 오열하게 만드는 사파리... 후...

**Comment by SenseCodeValue** [comment]
textarea도 아마 그럴꺼에요 ㅠ

**Comment by ddarkr** [comment]
@SenseCodeValue 한번 쫙 대응해야겠어요... 아무래도 아이폰 유저가 더 많을 듯 하니.... ㅋㅋㅋㅋ

**Comment by SenseCodeValue** [comment]
좋아요!!
