### ISSUE TITLE
app to web 테스트용 웹 사이트 개발

### ISSUE THREAD

**Issue by ddarkr** [depromeet/11th_7team_web#50]
## 설명

- app에서 web으로 데이터를 넘겨주는 시나리오를 테스트하기 위해 테스트 페이지를 구현합니다.
- pr 단에서 배포된 페이지를 통해 진행하며, 실제 머지까지는 하지 않습니다.

## 할 일

- [x] 데이터 받을 방법 고민
- [x] #58

**Comment by ddarkr** [comment]
## 데이터 받을 방법 ref

https://kyounghwan01.github.io/blog/React/react-native/react-native-webview
https://webruden.tistory.com/305

**Comment by SenseCodeValue** [comment]
저도 확인해보겠습니다! 감사합니다!
